### ISSUE TITLE
245cloud開発startガイド ってのを追加したい

### ISSUE THREAD

**Issue by fukajun** [pandeiro245/245cloud#200]
目的は、貢献したい人がスムーズに環境を整えれるようにしたい

この辺がREADME.mdに追加したい内容なんですが...
parse.com経由?でのfacebookログインとかってありますか？
facebookログイン周りで詰まりました。

以下 ↓

### 245cloud開発startガイド

mysql 使うヨロシ

1. Gemfile と config/environments/development.rb にある kintone の行はコメントアウト
2. config/database.yml 作成 => exampleで入れておきたい

```
development:
  adapter: mysql2
  encoding: utf8
  database: 245_dev
  username: root
  password:
```

3. bundle exec rake db:create
4. bundle exec rake db:migrate

5. Faceboo App Idを開発用に取得
  - domain: localhost
  - web site url; localhost:3001

6. parse.com を…… 新規アカウント作れない… オフっ
